### ISSUE TITLE
installation ov 1.1.16 fails with serialport module under vscode 1.61.2 on ubuntu 21.04

### ISSUE THREAD

**Issue by flokain** [pycom/pymakr-vsc#184]
## What are the steps to reproduce this issue?
1. install pymakr 1.1.16
2.
3.

## What happens?
install fails

## What were you expecting to happen?
installation succeeds w/o errors

## Any logs, error output, etc?
```
console.ts:137 [Extension Host] [PyMakr][serialport] import module...
console.ts:137 [Extension Host] [PyMakr][serialport] import module... failed Could not locate the bindings file. Tried:
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/build/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/build/Debug/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/build/Release/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/out/Debug/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/Debug/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/out/Release/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/Release/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/build/default/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/compiled/14.16.0/linux/x64/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node
 → /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/lib/binding/node-v89-linux-x64/bindings.node
console.ts:137 [Extension Host] [PyMakr][serialport] remove old bindings...
console.ts:137 [Extension Host] [PyMakr][serialport] download bindings...
console.ts:137 [Extension Host] [PyMakr][serialport] download bindings... success
console.ts:137 [Extension Host] [PyMakr][serialport] import module...
console.ts:137 [Extension Host] [PyMakr][serialport] import module... failed /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/build/Release/bindings.node)
console.ts:137 [Extension Host] [PyMakr][serialport] remove old bindings...
console.ts:137 [Extension Host] [PyMakr][serialport] build bindings in Node...
log.ts:301   ERR [Extension Host] [PyMakr][serialport] build bindings in Node failed Error: node-gyp failed to rebuild '/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `gyp` failed with exit code: 1


	at NodeGyp.rebuildModule (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:109:19)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async ModuleRebuilder.rebuildNodeGypModule (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/electron-rebuild/lib/src/module-rebuilder.js:94:9)
	at async Rebuilder.rebuildModuleAt (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/electron-rebuild/lib/src/rebuild.js:226:9)
	at async Rebuilder.rebuild (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/electron-rebuild/lib/src/rebuild.js:184:17)
	at async prepareSerialPort (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/lib/serialport/index.js:49:17)
	at async activate (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/pymakr.js:8:5)
console.ts:137 [Extension Host] [PyMakr][serialport] build bindings in Node failed Error: node-gyp failed to rebuild '/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `gyp` failed with exit code: 1


	at NodeGyp.rebuildModule (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:109:19)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async ModuleRebuilder.rebuildNodeGypModule (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/electron-rebuild/lib/src/module-rebuilder.js:94:9)
	at async Rebuilder.rebuildModuleAt (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/electron-rebuild/lib/src/rebuild.js:226:9)
	at async Rebuilder.rebuild (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/electron-rebuild/lib/src/rebuild.js:184:17)
	at async prepareSerialPort (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/lib/serialport/index.js:49:17)
	at async activate (/home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/pymakr.js:8:5)
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] [PyMakr][serialport] import module...
console.ts:137 [Extension Host] [PyMakr][serialport] import module... failed /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/build/Release/bindings.node: cannot open shared object file: No such file or directory
console.ts:137 [Extension Host] [PyMakr][serialport] remove old bindings...
localProcessExtensionHost.ts:335 Extension Host
console.ts:137 [Extension Host] [PyMakr][serialport] build bindings in terminal...
console.ts:137 [Extension Host] [PyMakr][serialport] build bindings in terminal... success
console.ts:137 [Extension Host] [PyMakr][serialport] import module...
console.ts:137 [Extension Host] [PyMakr][serialport] import module... failed /home/fkain/.vscode/extensions/pycom.pymakr-1.1.16/node_modules/@serialport/bindings/build/Release/bindings.node: cannot open shared object file: No such file or directory
notificationsAlerts.ts:42 There was an error with your serialport module, Pymakr will likely not work properly. Please try to install again or report an issue on our github (see developer console for details)
onDidChangeNotification @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
fire @ event.ts:577
addNotification @ notifications.ts:206
notify @ notificationService.ts:137
(anonymous) @ mainThreadMessageService.ts:86
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:95 Activating extension 'pycom.pymakr' failed: All solutions failed for serialport.
$onExtensionActivationError @ mainThreadExtensionService.ts:95
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
_ @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```

## Any other comments?
vscode is installed via snap

## What versions of software are you using?

Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-38-lowlatency snap

pymakr 1.1.16

**Comment by flokain** [comment]
i can confirm, that installing same vscode version via.deb package worked. so there must be an issue with snap

**Comment by jakobrosenberg** [comment]
Sorry about the slow reply @flokain 

Thanks for the feedback. I didn't know there were issues related to snap, so I'll add that to the readme.
