### ISSUE TITLE
Pymakr: Folder problems on Arch Linux Code - OSS

### ISSUE THREAD

**Issue by g0r3** [pycom/pymakr-vsc#199]
Pymakr does not seem to work with the VS Code version from the official Arch Linux repo. Not sure if it is a problem of VS Code or the extension, so I create a bug report here.

## What are the steps to reproduce this issue?
1. Install Code - OSS on Arch Linux (package `code`)
2. Install package `code-marketplace`
3. Install pymakr from the vscode extensions store

## What happens?
Pymakr fails to run properly. Global settings are not opening. The Pymakr terminal is not reacting to any input.

## Any logs, error output, etc?
After studying the verbose output of VS Code I found out, that Pymakr (VS Code?) is expecting the settings folder to be `.config/Code` . But Code-OSS creates a folder named `.config/Code OSS` for its settings, usually there is no `.config/Code` directory.
```[22061:0206/115345.590848:INFO:CONSOLE(75)] "%c[Extension Host] %c[warning] SettingsWrapper | Error processing Config file:/home/User/.config/Code/User/pymakr.json %c(at Logger.log (/home/User/.vscode-oss/extensions/pycom.pymakr-1.1.17/lib/helpers/logger.js:22:15)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (75)
[22061:0206/115348.090941:INFO:CONSOLE(75)] "%c[Extension Host] %c[warning] SettingsWrapper | Error processing Config file:/home/User/.config/Code/User/pymakr.json %c(at Logger.log (/home/User/.vscode-oss/extensions/pycom.pymakr-1.1.17/lib/helpers/logger.js:22:15)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (75)
[22061:0206/115350.636641:INFO:CONSOLE(75)] "%c[Extension Host] %c[warning] SettingsWrapper | Error processing Config file:/home/User/.config/Code/User/pymakr.json %c(at Logger.log (/home/User/.vscode-oss/extensions/pycom.pymakr-1.1.17/lib/helpers/logger.js:22:15)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (75)
[22061:0206/115353.091705:INFO:CONSOLE(75)] "%c[Extension Host] %c[warning] SettingsWrapper | Error processing Config file:/home/User/.config/Code/User/pymakr.json %c(at Logger.log (/home/User/.vscode-oss/extensions/pycom.pymakr-1.1.17/lib/helpers/logger.js:22:15)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (75)
```

Symlinking  `.config/Code OSS` to `.config/Code` seems to at least partly fix the issue. Still in the setup process, so I am not sure if everything works.

## What versions of software are you using?

**Operating system:**
Arch Linux

**VSCode version:**
Code - OSS 1.64.0-1
code-marketplace 1.54.3-4
**Pymakr version:**
1.1.17

**Comment by redghc** [comment]
Do you have NodeJS installed? If you don't have it installed you can use NVM:
https://github.com/nvm-sh/nvm

Then try opening a new terminal (bash/zsh)
Run the `code` command, which will open vscode, now install PyMakr again.
![imagen](https://user-images.githubusercontent.com/94464560/161135917-2e7d4bdc-1e8d-42c6-b03a-aec50ecf045e.png)

For some reason I have noticed that Code-oss/vscode/vscodium do not correctly detect the node installation, even when it is in the PATH, which causes problems with the PyMakr terminal
