### ISSUE TITLE
Command 'pymakr.__AnyCommand__' not found

### ISSUE THREAD

**Issue by redghc** [pycom/pymakr-vsc#202]
## What are the steps to reproduce this issue?
1. Install vscode
2. Install Pymakr extension from marketplace
3. Execute any Pymkr command (ctrl + shift + p)

## What happens?
Get error "Command 'pymakr.__anycommand__' not found
Modifications are also not shown in the vscode status bar

## What were you expecting to happen?
Execute any command of pymakr

## Any other comments?
NodeJs installed using NVM
Python installed using pyenv

See this issue: https://github.com/pycom/pymakr-vsc/issues/188
However I don't have an ARM processor so I think it's a different problem.

Do the same procedure on an intel i3 processor, getting the same result.

## What versions of software are you using?

**Operating system:**
OS: Arch Linux x86_64 
Host: B450 AORUS ELITE 
Kernel: 5.15.31-1-lts 
DE: Plasma 5.24.3 
WM: KWin 
CPU: AMD Ryzen 3 1300X (4) @ 3.500GHz 
GPU: AMD ATI Radeon RX 570

**VSCode version:**
Versión: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Fecha: 2022-03-10T15:36:26.048Z
Electrón: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.31-1-lts

**Pymakr version:**
v1.1.17
v2.8.1 - Preview
(Both fail)

**Comment by berbert-arthur** [comment]
Tenho o mesmo problema...

**Comment by jakobrosenberg** [comment]
@redghc I just tried installing Pymakr 1 in VSCode and I noticed that it was no longer enabled by default. Would you check that the plugin has been enabled and that your VSCode has been reloaded?

**Comment by redghc** [comment]
@jakobrosenberg 

Sure the extension is enabled and restart VSCode.

----
Using the  v2.8.1 - Preview

I noticed the following: 
Opening the debug console get this error.
![error1](https://user-images.githubusercontent.com/94464560/160999982-584d5e39-72a5-48f9-bdec-3fcb95036680.png)

Importing "stateManager"

![Screenshot_20220331_002305](https://user-images.githubusercontent.com/94464560/161000554-4bd1e51f-3050-427d-b57b-8a9d802d0fe3.png)

However the correct name of the file is "StateManager"
![Screenshot_20220331_002511](https://user-images.githubusercontent.com/94464560/161000742-b394612b-e7ac-4bca-b189-0481aa202e00.png)


Changing "stateManager" to "StateManager"
In this files

- /src/Device.js
- /src/Project.js
![Screenshot_20220331_002705](https://user-images.githubusercontent.com/94464560/161001089-26aa5a10-9335-4867-8f6e-7bda2cbd1680.png)

Now the console error is fixed.

-----

However the main error continues to appear and now there is no error in the console. 


![Screenshot_20220331_002924](https://user-images.githubusercontent.com/94464560/161001491-6a0c569b-193e-4c8b-938c-8ea2101ab580.png)

**Comment by jakobrosenberg** [comment]
Good catch on the capitalization. The command manifest was copied from the old Pymakr v1. I think it might be time to clean up all the unused commands now. 😅

I'll push a fix for this and get back to you.

**Comment by jakobrosenberg** [comment]
V2.8.2 is out now. I hope this fixes the issues. At least for v2.

**Comment by berbert-arthur** [comment]
O processo de terminal "node 'c:\Users\arthu\.vscode\extensions\pycom.pymakr-preview-2.8.2\src\terminal\client.js', 'serial', 'COM2'" foi terminado com o código de saída: 1.
![image](https://user-images.githubusercontent.com/73605198/161056288-187946fe-5a6a-43d9-8309-f6e5504690e4.png)

**Comment by berbert-arthur** [comment]
![image](https://user-images.githubusercontent.com/73605198/161060243-8b7186f3-7453-4bd2-a950-744384940640.png)

**Comment by berbert-arthur** [comment]
![image](https://user-images.githubusercontent.com/73605198/161062823-6a838f9e-e930-462e-bc49-50e2a42ed6bf.png)

**Comment by jakobrosenberg** [comment]
Thanks @berbert-arthur . This has been fixed in v2.8.3.

**Comment by berbert-arthur** [comment]
[Pymakr] Failed to run command: uploadProject. Reason: Traceback (most recent call last): File "<stdin>", line 1, in <module> OSError: [Errno 2] ENOENT. Please see logs for info.

**Comment by berbert-arthur** [comment]
![image](https://user-images.githubusercontent.com/73605198/161070490-dc496d5b-99cf-4add-9f8b-fbbdf9b69473.png)

**Comment by jakobrosenberg** [comment]
Seems there's an issue with the paths. I'll try get a fix released tomorrow.

**Comment by redghc** [comment]
@jakobrosenberg

With the last update some parts of the extension already work (Thank you very much!)

However, there are still some errors. I leave you a summary of those that I have detected. 

configureDevice
-----
![imagen](https://user-images.githubusercontent.com/94464560/161178859-38b21aeb-b6fa-44ad-8e24-d5df0ddb8647.png)

Steps:
![imagen](https://user-images.githubusercontent.com/94464560/161179590-584bc114-9029-4367-8292-747a11dc0575.png)
Then select username or password.

![imagen](https://user-images.githubusercontent.com/94464560/161179817-21e57ead-8a05-42af-9d7a-eb8b922b7cef.png)
I add some console logs and it seems that it is trying to execute the function menus["username"]  or menus["password"] 

Based on the above and the screenshot below, it attempts to execute a nonexistent function. (Only exist `main` and `autoConnect`)
![imagen](https://user-images.githubusercontent.com/94464560/161180000-be41adc7-0a94-44c1-98b6-375561ba8965.png)


eraseDevice
-----
![imagen](https://user-images.githubusercontent.com/94464560/161180234-b4cb9fce-697e-4f1b-bedf-4af8f9632065.png)

Select any of the projects and you get these errors 
![imagen](https://user-images.githubusercontent.com/94464560/161180387-d477415f-4bfc-4ea5-9392-eaf5c8a3fc56.png)

I hope this helps in the development of the new version, I would like to support you but I haven't worked on the development of extensions for vscode, I don't have much experience :c .

**Comment by jakobrosenberg** [comment]
Thanks much for the feedback!! This is really helpful.

Telnet is currently not supported. The micropython library that we use, does support wireless, but not through a direct telnet connection. I don't know if telnet is a popular feature, but we'll discuss it internally soon. Any feedback on this would greatly appreciated!

The erase feature should be working, so it looks like you found a bug. I'll have a look today.

FWIW this is also my first VSCode extension. Gotta say I love the architecture and API.

**Comment by jakobrosenberg** [comment]
@redghc I'm unable to replicate the erase device bug. Do you have any logs you can share?

**Comment by redghc** [comment]
The steps to duplicate are:

- Open vscode
- Connect the device with click on the lightning.
- Right click -> Erase device -> Empty project 

Sure here is some screenshoot from developer tools.

![imagen](https://user-images.githubusercontent.com/94464560/161309347-55807d1d-dcfe-482c-9311-52daea24fecb.png)

> er, Traceback (most recent call last):
  File "<stdin>", line 20, in <module>
  File "<stdin>", line 6, in rmdir
OSError: -2

> Unable to log remote console arguments Output omitted for an object that cannot be inspected ('TypeError: Cannot read properties of undefined (reading 'getNearest')')

> PyMakr > command > Error: Traceback (most recent call last):
  File "<stdin>", line 20, in <module>
  File "<stdin>", line 6, in rmdir
OSError: -2

-----
I was reviewing the code and I think the problem originates from the execution of this function. 

**Line 83**
![imagen](https://user-images.githubusercontent.com/94464560/161310159-b1498018-9780-4225-bc62-bff16739b3fa.png)


-----
I tried from the "Open terminal log" option, but the file is empty. 
![imagen](https://user-images.githubusercontent.com/94464560/161309238-cb4bfe1b-cf7c-40b8-9ef5-aafa1df4ebd3.png)

![imagen](https://user-images.githubusercontent.com/94464560/161309301-58beeb48-1656-4fdf-9fd3-b7575dbbd067.png)

I think it has to do with this 

> Unable to log remote console arguments Output omitted for an object that cannot be inspected ('TypeError: Cannot read properties of undefined (reading 'getNearest')')

I hope this helps

**Comment by jakobrosenberg** [comment]
Thanks for catching the "open terminal log" misnomer. 👍 It should really be "open terminal history". I'll include a correction in the next patch.

**Comment by jakobrosenberg** [comment]
@redghc are you still getting the `erase device` error? I haven't been able to reproduce it locally

**Comment by redghc** [comment]
@jakobrosenberg 

If I still have the same error.

![image](https://user-images.githubusercontent.com/94464560/162481803-b898c83a-119b-421f-a404-7571acb40f52.png)

![image](https://user-images.githubusercontent.com/94464560/162481846-3ba8273c-4721-4693-a718-ef2c45510643.png)

-----
In fact I found another problem that I think may be related.

If I execute the action "Upload Project"

Get this error:
![image](https://user-images.githubusercontent.com/94464560/162482479-54fb0557-7737-402e-97c4-bc6c9ab706b5.png)

![image](https://user-images.githubusercontent.com/94464560/162482483-1e3506bd-21df-418c-9c20-c170628f046f.png)

However from what I could notice the project does upload correctly.

Note: This action works fine in the v1.1.8, 

And from what I was able to see, in v1.1.8, the "Upload" action also performs file deletion, which I think is the problem with the "Preview Version" that it can't delete files.

-----

**Note: The action "Download project" works fine.**
But it doesn't throw any notification when it finishes downloading the project, I think it would be good to place some notification that alerts that the download action is finished.

-----

**Comment by RaspChris** [comment]
same problem with MacOS 12.3.1, VSC 1.66.2, pymakr v1.1.18
No functional command with pymakr.
Thank you
Chris

**Comment by jakobrosenberg** [comment]
@RaspChris are you getting a no functional command error with with Pymakr v2?

**Comment by RaspChris** [comment]
Thank you.
We followed this same problem in the Atom section (I tried with both Atom and VSC)  and finally concluded that the board was faulty. I contacted support.

**Comment by dan-phd** [comment]
Possibly similar to this issue, I cannot create a project because command "pymakr.createProjectPrompt" not found. Nothing happens clicking the GUI buttons, but I get the error when selecting from the Command Palette.
I am running latest versions of everything (Windows 11 Version 10.0.22000, Visual Studio Code 1.70.2 and PyMakr v2.22.5).

**Comment by jakobrosenberg** [comment]
Hi @dan-phd , I expect your install may have been corrupted somehow. Could you try uninstall all `Pymakr` and `Pymakr - Preview` extensions, restart VSCode and then reinstall?

**Comment by dan-phd** [comment]
> Hi @dan-phd , I expect your install may have been corrupted somehow. Could you try uninstall all `Pymakr` and `Pymakr - Preview` extensions, restart VSCode and then reinstall?

Thanks @jakobrosenberg however that did not work, I also tried disabling all other extensions and the preview version, still did not work. Then I tried installing a previous version, going back to v2.12.3 worked! More recent versions (2.22.2, 2.22.4 and 2.22.5) do not. Hopefully there is scope now to see what changed between 2.12.3 and 2.22.2 ?

**Comment by markusfloer** [comment]
<img width="433" alt="Capture" src="https://user-images.githubusercontent.com/37398225/187910302-d3fce9cc-dc7c-4d0b-87b3-3af975a69839.PNG">

**Comment by markusfloer** [comment]
> <img alt="Capture" width="433" src="https://user-images.githubusercontent.com/37398225/187910302-d3fce9cc-dc7c-4d0b-87b3-3af975a69839.PNG">

I have the latest release of pymakr installed on vscode. Trying to upload a new project to gpy device, I'm not allowed to press the upload button, so trying to delete existing project. This is the error message that appears.

**Comment by jakobrosenberg** [comment]
Hi @dan-phd . Apologies. I completely missed your last reply. If you switch to the preview version, you should be able to pinpoint the exact patch that broke your setup. From there I can have a look and see what happened.

@markusfloer that also looks like the extension didn't install properly. If previous versions work for you, I should be able to fix it - granted that you're able to identify the last working version. I suspect it's the same issue you're facing.

**Comment by mp3user** [comment]
Fresh install latest extension is work but after I disable and then enable it and now it completly broken.
Any command is failed with "command pymekr.name not found".
Ive try reinstall extension with older version and vscode as well

**Comment by aka13-404** [comment]
Happe

> Possibly similar to this issue, I cannot create a project because command "pymakr.createProjectPrompt" not found. Nothing happens clicking the GUI buttons, but I get the error when selecting from the Command Palette. I am running latest versions of everything (Windows 11 Version 10.0.22000, Visual Studio Code 1.70.2 and PyMakr v2.22.5).

Happens to me as well. Preview seems to work though.
